import { OBDCommand } from './types';
import {
  unknown,
  power_switch,
  gear_position,
  bat_12v_voltage,
  bat_12v_current,
  ambient_temp,
  estimated_ac_power,
  estimated_ptc_power,
  aux_power,
  ac_power,
  plug_state,
  charge_mode,
  obc_out_power,
  ac_on,
  odometer,
  tp_fr,
  tp_fl,
  tp_rr,
  tp_rl,
  range_remaining,
  lbc,
} from './decoders';

export const AZE0_24KWH_COMMANDS: OBDCommand[] = [
  { name: 'unknown',             description: 'Mystery command',                  commandHex: '0210C0',   header: '797', expectedBytes: 0,  decoder: unknown },
  { name: 'power_switch',        description: 'Power switch status',               commandHex: '03221304', header: '797', expectedBytes: 5,  decoder: power_switch },
  { name: 'gear_position',       description: 'Gear position',                     commandHex: '03221156', header: '797', expectedBytes: 4,  decoder: gear_position },
  { name: 'bat_12v_voltage',     description: '12V battery voltage',               commandHex: '03221103', header: '797', expectedBytes: 4,  decoder: bat_12v_voltage },
  { name: 'bat_12v_current',     description: '12V battery current',               commandHex: '03221183', header: '797', expectedBytes: 5,  decoder: bat_12v_current },
  { name: 'ambient_temp',        description: 'Ambient temperature',               commandHex: '0322115d', header: '797', expectedBytes: 4,  decoder: ambient_temp },
  { name: 'estimated_ac_power',  description: 'Estimated AC system power',         commandHex: '03221261', header: '797', expectedBytes: 4,  decoder: estimated_ac_power },
  { name: 'estimated_ptc_power', description: 'Estimated PTC system power',        commandHex: '03221262', header: '797', expectedBytes: 4,  decoder: estimated_ptc_power },
  { name: 'aux_power',           description: 'Auxiliary equipment power',         commandHex: '03221152', header: '797', expectedBytes: 4,  decoder: aux_power },
  { name: 'ac_power',            description: 'AC system power',                   commandHex: '03221151', header: '797', expectedBytes: 4,  decoder: ac_power },
  { name: 'plug_state',          description: 'Plug state of J1772 socket',        commandHex: '03221234', header: '797', expectedBytes: 4,  decoder: plug_state },
  { name: 'charge_mode',         description: 'Charging mode',                     commandHex: '0322114e', header: '797', expectedBytes: 4,  decoder: charge_mode },
  { name: 'obc_out_power',       description: 'On-board charger output power',     commandHex: '03221236', header: '797', expectedBytes: 5,  decoder: obc_out_power },
  { name: 'ac_on',               description: 'AC status',                         commandHex: '03221106', header: '797', expectedBytes: 5,  decoder: ac_on },
  { name: 'odometer',            description: 'Total odometer reading (km)',        commandHex: '03220e01', header: '743', expectedBytes: 6,  decoder: odometer },
  { name: 'tp_fr',               description: 'Tyre pressure front right',         commandHex: '03220e25', header: '743', expectedBytes: 4,  decoder: tp_fr },
  { name: 'tp_fl',               description: 'Tyre pressure front left',          commandHex: '03220e26', header: '743', expectedBytes: 4,  decoder: tp_fl },
  { name: 'tp_rr',               description: 'Tyre pressure rear right',          commandHex: '03220e27', header: '743', expectedBytes: 4,  decoder: tp_rr },
  { name: 'tp_rl',               description: 'Tyre pressure rear left',           commandHex: '03220e28', header: '743', expectedBytes: 4,  decoder: tp_rl },
  { name: 'range_remaining',     description: 'Remaining range (km)',               commandHex: '03220e24', header: '743', expectedBytes: 13, decoder: range_remaining },
  { name: 'lbc',                 description: 'Li-ion battery controller',          commandHex: '022101',   header: '79B', expectedBytes: 53, decoder: lbc },
];
